### ISSUE TITLE
Unable to tap cask on Apple silicon

### ISSUE THREAD

**Issue by fangel** [cyberark/homebrew-tools#41]
## Summary

If you try to do `brew tap cyberark/tools` on a Apple sillicon computer (M1-powered) you get an error about missing `url` in Serverless-broker

## Steps to Reproduce

1. `brew tap cyberark/tools`

It's possible it can be reproduced on non-Apple silicon using `arch -arm64 brew tap cyberark/tools` (you'll probably need to untap first, then tap with the arch changed)

## Expected Results

The cask is tapped successfully.

## Actual Results

```
Error: Invalid formula: /opt/homebrew/Library/Taps/cyberark/homebrew-tools/secretless-broker.rb
formulae require at least a URL
```

This is likely because the formulae for secreless-broken only defines the `url` inside a `if` that looks for the hardware arch. 

If the app in question only exists for Intel-powered Macs, it's might be possible to use something like `depends_on arch: :intel` in the Formulae (see https://docs.brew.sh/Cask-Cookbook#depends_on-arch). 
It will still need to set the `url`-property, but it'll refuse to install on Apple silicon, which is better than the whole cask failing.

## Reproducible

   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Environment setup

* Apple Silicon powered laptop

**Comment by rpothier** [comment]
With PR [secretless-broker 1456](https://github.com/cyberark/secretless-broker/pull/1456) secretless-broker.rb should get updated and should fix the issue when released.

**Comment by tabacco** [comment]
I see that PR is merged, but there are still no arm64 builds available and the tap still won't work on arm macs.

**Comment by rpothier** [comment]
@tabacco The components get updated in homebrew when they are [released](https://github.com/cyberark/secretless-broker/blob/main/CONTRIBUTING.md#releasing). We have scheduled the components for release.

**Comment by dzasorki** [comment]
Hey team, when approximately can we see this PR on prod? Does anyone know the approximate date?
Thank you!

**Comment by rpothier** [comment]
Hi @dzasorki Secretless-broker and summon-aws-secrets are scheduled to be released in the next two weeks. The other components have already been updated for Apple silicon.

**Comment by tabacco** [comment]
Hi, you closed this, but the issue doesn't appear to be resolved:

```
 brew tap cyberark/tools
==> Tapping cyberark/tools
Cloning into '/opt/homebrew/Library/Taps/cyberark/homebrew-tools'...
remote: Enumerating objects: 292, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 292 (delta 49), reused 88 (delta 48), pack-reused 189
Receiving objects: 100% (292/292), 68.98 KiB | 811.00 KiB/s, done.
Resolving deltas: 100% (146/146), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/cyberark/homebrew-tools/secretless-broker.rb
formulae require at least a URL
Error: Cannot tap cyberark/tools: invalid syntax in tap!
```

**Comment by tabacco** [comment]
Looks like the last two secretless-broker releases were marked as pre-release, so they didn't update the homebrew formula

**Comment by tabacco** [comment]
It works! Thank you very much!
